baseURL = "https://wilspi.com"
languageCode = "en-us"
title = "Sourabh Deokar"
theme = "PaperMod"

enableEmoji = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false


## Google Analytics
googleAnalytics = "UA-51915090-3"


[params]
title = "नमस्ते"
author = "wilspi"
# description = "I'm Sourabh Deokar"
profilePicture = "images/dp.jpg"

env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
#images = ["<link or path of image for opengraph, twitter-cards>"]

defaultTheme = "auto" # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
disableSpecial1stPost = true
comments = false
hidemeta = false
showtoc = false
tocopen = false

keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/cover.jpg"]

[params.profileMode]
enabled = false # needs to be explicitly set
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "images/cover.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"
# buttons:
#         - name: Posts
#           url: posts
#         - name: Tags
#           url: tags

# home-info mode
# homeInfoParams:
#     Title: "Hi there \U0001F44B"
#     Content: Welcome to my blog


## Math settings
[params.math]
enable = false
use = "katex"


## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/wilspi/"

[[params.socialIcons]]
icon = "fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/channel/UCMg3idz-2FlreEeHY_0i13w"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/iamwilspi"

# [[params.socialIcons]]
# icon = "fa-instagram"
# title = "Instagram"
# url = "https://www.instagram.com/wilspi/"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Notes"
  identifier = ""
  weight = 100
  url = "https://notes.wilspi.com"

  # [[menu.main]]
  # name = "Posts"
  # weight = 200
  # identifier = "posts"
  # url = "/post/"

  # [[menu.main]]
  # name = "About"
  # weight = 300
  # identifier = "about"
  # url = "/about/"
