baseURL = "https://wilspi.com"
languageCode = "en-us"
title = "Sourabh Deokar"
theme = "anatole"
enableEmoji = true
enableRobotsTXT = true


## Google Analytics
googleAnalytics = "UA-51915090-3"


[params]
title = "नमस्ते"
author = "wilspi"
# description = "I'm Sourabh Deokar"
profilePicture = "images/dp.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/cover.jpg"]


## Math settings
[params.math]
enable = false
use = "katex"


## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/wilspi/"

[[params.socialIcons]]
icon = "fa-youtube"
title = "Youtube"
url = "https://www.youtube.com/channel/UCMg3idz-2FlreEeHY_0i13w"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/iamwilspi"

# [[params.socialIcons]]
# icon = "fa-instagram"
# title = "Instagram"
# url = "https://www.instagram.com/wilspi/"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Notes"
  identifier = ""
  weight = 100
  url = "https://notes.wilspi.com"

  # [[menu.main]]
  # name = "Posts"
  # weight = 200
  # identifier = "posts"
  # url = "/post/"

  # [[menu.main]]
  # name = "About"
  # weight = 300
  # identifier = "about"
  # url = "/about/"
